# Generated by Django 4.1.3 on 2022-11-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_service', models.CharField(choices=[('Make-up', 'Makeup'), ('Nails', 'Nail service'), ('Hair', 'Hair service'), ('Cosmetology', 'Cosmetology'), ('Massage', 'Massage')], help_text='Select type of service', max_length=30)),
                ('service_price', models.IntegerField(help_text='Enter yuor price')),
                ('service_duration', models.IntegerField(help_text='Enter service duration')),
                ('name_of_master', models.TextField(help_text='Enter the name of master', max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='checkin_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='is_checkout',
            new_name='it_finished',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='checkout_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.service'),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
