# Generated by Django 4.1.3 on 2022-11-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_service_rename_clients_client_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
