# Generated by Django 4.1.3 on 2022-11-08 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_alter_clients_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this client', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this service', primary_key=True, serialize=False),
        ),
    ]
